export const VARIABLES: object[] = [
  // {name: 'Timestamp', value: 'timestamp', units: 'epoch'},
  {name: 'Temperature', value: 'air_temperature', units: 'F', convM: 9 / 5 , convA: 32},
  {name: 'Barometric Pressure', value: 'barometric_pressure', units: ''},
  {name: 'Station Pressure', value: 'station_pressure', units: ''},
  {name: 'Sea Level Pressure', value: 'sea_level_pressure', units: ''},
  {name: 'Relative Humidity', value: 'relative_humidity', units: ''},
  {name: 'Precipitation', value: 'precip', units: ''},
  {name: 'Precipitation (Last hour)', value: 'precip_accum_last_1hr', units: ''},
  {name: 'Precipitation (Today)', value: 'precip_accum_local_day', units: ''},
  {name: 'Precipitation (Yesterday)', value: 'precip_accum_local_yesterday', units: ''},
  {name: 'Precipitation (Yesterday Final)', value: 'precip_accum_local_yesterday_final', units: ''},
  {name: 'Precipitation minutes (Today)', value: 'precip_minutes_local_day', units: ''},
  {name: 'Precipitation minutes (Yesterday)', value:'precip_minutes_local_yesterday', units: ''},
  {name: 'Precipitation minutes (Yesterday Final)', value: 'precip_minutes_local_yesterday_final', units: ''},
  {name: 'Precipitation Analysis', value: 'precip_analysis_type_yesterday', units: ''},
  {name: 'Wind Average', value: 'wind_avg', units: ''},
  {name: 'Wind Direction', value: 'wind_direction', units: ''},
  {name: 'Wind Gust', value: 'wind_gust', units: ''},
  {name: 'Wind Lull', value: 'wind_lull', units: ''},
  {name: 'Solar Radiation', value: 'solar_radiation', units: ''},
  {name: 'UV', value: 'uv', units: ''},
  {name: 'Brightness', value: 'brightness', units: ''},
  {name: 'Last Lightning Strike (time)', value: 'lightning_strike_last_epoch', units: ''},
  {name: 'Last Lightning Strike (distance)', value: 'lightning_strike_last_distance', units: ''},
  {name: 'Lightning Strike Count', value: 'lightning_strike_count', units: ''},
  {name: 'Lightning Strikes (Last 3 hours)', value: 'lightning_strike_count_last_3hr', units: ''},
  {name: 'Feels like', value: 'feels_like', units: 'C'},
  {name: 'Heat Index', value: 'heat_index', units: 'C'},
  {name: 'Wind Chill', value: 'wind_chill', units: 'C'},
  {name: 'Dew Point', value: 'dew_point', units: 'C'},
  {name: 'Wet bulb temperature', value: 'wet_bulb_temperature', units: 'C'},
  {name: 'Change in Temperature', value: 'delta_t', units: 'C'},
  {name: 'Air Density', value: 'air_density', units: ''},
];

